  services:
    backend:
      build: ./backend
      ports:
        - "3001:3000"
      volumes:
        # Persist the backend's 'data' folder to a fixed location on the host
        - ./backend/public:/app/public
      environment:
        - NODE_ENV=production
      restart: always

    frontend:
      build: ./frontend
      ports:
        - "4201:80"